sudo: required

before_install:
    - docker pull tgrogers/gpgpu-sim_regress:volta_update

language: cpp


matrix:
  include:
    - services: docker
      env:
        - CUDA_INSTALL_PATH=/usr/local/cuda-4.2/
        - PTXAS_CUDA_INSTALL_PATH=/usr/local/cuda-4.2/
    - services: docker
      env:
        - CUDA_INSTALL_PATH=/usr/local/cuda-9.1/
        - PTXAS_CUDA_INSTALL_PATH=/usr/local/cuda-9.1/

script: docker run -v `pwd`:/home/runner/gpgpu-sim_simulations:rw tgrogers/gpgpu-sim_regress:volta_update /bin/bash -c "chown -R runner /home/runner/gpgpu-sim_simulations; su - runner -c 'export CUDA_INSTALL_PATH=$CUDA_INSTALL_PATH && export PTXAS_CUDA_INSTALL_PATH=$PTXAS_CUDA_INSTALL_PATH && export PATH=$CUDA_INSTALL_PATH/bin:$PATH && export LD_LIBRARY_PATH=$CUDA_INSTALL_PATH/lib && source /home/runner/gpgpu-sim_simulations/benchmarks/src/setup_environment && make -C /home/runner/gpgpu-sim_simulations/benchmarks/src clean && make -j -C /home/runner/gpgpu-sim_simulations/benchmarks/src all'"
